import { RawLead } from './types';

export const rawLeads: RawLead[] = [
  {
    "title": "Fit-Good",
    "totalScore": 4.9,
    "reviewsCount": 934,
    "street": "11 Rue de la Grande Bretagne",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://fit-good.fr/",
    "phone": "+33 2 40 50 46 99",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Fit-Good&query_place_id=ChIJSx3varnvBUgR9Xgt99M3FKU"
  },
  {
    "title": "Batiste Zrn coach sportif santé",
    "totalScore": null,
    "reviewsCount": 0,
    "street": "11 Rue de la Grande Bretagne",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://batistezerren.wixsite.com/coaching",
    "phone": "+33 6 65 51 03 99",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Batiste%20Zrn%20coach%20sportif%20sant%C3%A9&query_place_id=ChIJo5Hux_XvBUgR7xO_g5ok4pQ"
  },
  {
    "title": "Coach Chloé - COACH SPORTIVE Nantes - Sport Santé",
    "totalScore": 5.0,
    "reviewsCount": 14,
    "street": "Bd Jules Verne",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://coachchloe-sportsante.fr/",
    "phone": "+33 6 58 77 70 90",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach%20Chlo%C3%A9%20-%20COACH%20SPORTIVE%20Nantes%20-%20Sport%20Sant%C3%A9&query_place_id=ChIJ43TfpwPvBUgR0yE5oR7sypM"
  },
  {
    "title": "LIFTRAINER - Coach sportif spécialisé en Street Workout, Calisthenics, Street Lifting, Force",
    "totalScore": 5.0,
    "reviewsCount": 80,
    "street": "83 Rue du Perray",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://liftrainer.com/",
    "phone": "+33 6 83 89 08 44",
    "categoryName": "Coaching professionnel",
    "url": "https://www.google.com/maps/search/?api=1&query=LIFTRAINER%20-%20Coach%20sportif%20sp%C3%A9cialis%C3%A9%20en%20Street%20Workout%2C%20Calisthenics%2C%20Street%20Lifting%2C%20Force&query_place_id=ChIJbeFQ5hHvBUgRaLlcwugrB0M"
  },
  {
    "title": "Gaia ATHLETIC TRAINING - Coach sportif/Préparation aux concours/Préparation physique/Réathlétisation",
    "totalScore": 5.0,
    "reviewsCount": 9,
    "street": "La beaujoire",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://gaia-athletictraining.com/",
    "phone": "+33 6 78 30 19 78",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Gaia%20ATHLETIC%20TRAINING%20-%20Coach%20sportif%2FPr%C3%A9paration%20aux%20concours%2FPr%C3%A9paration%20physique%2FR%C3%A9athl%C3%A9tisation&query_place_id=ChIJSb2Bzg3vBUgR8YVHHOWCJys"
  },
  {
    "title": "NEPTUNE COACHING - Coaching Sportif à Domicile / Salle / Extérieur",
    "totalScore": 5.0,
    "reviewsCount": 20,
    "street": "Rue des Acacias",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.neptunecoaching.fr/",
    "phone": "+33 6 14 35 55 97",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=NEPTUNE%20COACHING%20-%20Coaching%20Sportif%20%C3%A0%20Domicile%20%2F%20Salle%20%2F%20Ext%C3%A9rieur&query_place_id=ChIJu_UrwA_vBUgR-mIpfrORz6s"
  },
  {
    "title": "Océane Fitness - Coach Sportive pour Femmes",
    "totalScore": 5.0,
    "reviewsCount": 79,
    "street": "5 All. Gounod",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://oceanefitness.fr/",
    "phone": "+33 6 35 36 00 46",
    "categoryName": "Coach personnel pour femmes",
    "url": "https://www.google.com/maps/search/?api=1&query=Oc%C3%A9ane%20Fitness%20-%20Coach%20Sportive%20pour%20Femmes&query_place_id=ChIJV_4mhE7vBUgRBOy2vczMhaw"
  },
  {
    "title": "Mindteam Form&Tech | Salle de sport et coaching sportif à Nantes",
    "totalScore": 4.9,
    "reviewsCount": 106,
    "street": "91 Bd de la Prairie au Duc",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://mindteamformettech.fr/",
    "phone": "+33 2 85 37 62 70",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Mindteam%20Form%26Tech%20%7C%20Salle%20de%20sport%20et%20coaching%20sportif%20%C3%A0%20Nantes&query_place_id=ChIJVYDpeqTwBUgR5Qq0DftsMgQ"
  },
  {
    "title": "Fabien Arava — Coach Sportif à Nantes",
    "totalScore": 5.0,
    "reviewsCount": 133,
    "street": "1 Rue Marie Curie",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://fabien-coach-sportif.fr/",
    "phone": "+33 6 44 81 65 90",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Fabien%20Arava%20%E2%80%94%20Coach%20Sportif%20%C3%A0%20Nantes&query_place_id=ChIJV4TDASDoBUgRLDt7Przuv9s"
  },
  {
    "title": "Pierre Allaire Coaching Sportif",
    "totalScore": 5.0,
    "reviewsCount": 125,
    "street": "34 Bd Jean Ingres",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://pierreallaire-coaching.fr/",
    "phone": "+33 6 40 26 21 27",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Pierre%20Allaire%20Coaching%20Sportif&query_place_id=ChIJ2-fDio7wBUgRhvkQ1t5odJ4"
  },
  {
    "title": "Art du Corps - Coaching sportif et nutritionnel à Nantes",
    "totalScore": 5.0,
    "reviewsCount": 16,
    "street": "1 Bd de Berlin",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://artducorps.fr/",
    "phone": "+33 6 64 50 20 87",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Art%20du%20Corps%20-%20Coaching%20sportif%20et%20nutritionnel%20%C3%A0%20Nantes&query_place_id=ChIJFQINWb_-BUgRWRone0lgq1s"
  },
  {
    "title": "Coach Sportif Nantes - Stephane Coach Fitness & Gym Domicile, Extérieur & En Salle",
    "totalScore": 5.0,
    "reviewsCount": 55,
    "street": "1 Bd de Berlin",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://www.coach-sportif-nantes.fr/",
    "phone": "+33 6 84 32 08 09",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach%20Sportif%20Nantes%20-%20Stephane%20Coach%20Fitness%20%26%20Gym%20Domicile%2C%20Ext%C3%A9rieur%20%26%20En%20Salle&query_place_id=ChIJS7HROa_-BUgR6qP9ue1cWcU"
  },
  {
    "title": "I Training - Coaching sportif et préparation physique à Nantes",
    "totalScore": 5.0,
    "reviewsCount": 47,
    "street": "1 Bd de Berlin",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://itraining.fr/",
    "phone": "+33 6 20 40 72 92",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=I%20Training%20-%20Coaching%20sportif%20et%20pr%C3%A9paration%20physique%20%C3%A0%20Nantes&query_place_id=ChIJH8SEVb_-BUgRt_Zu6vB8ORs"
  },
  {
    "title": "Coach Sportif Nantes Ouest SPORTADOM",
    "totalScore": 4.8,
    "reviewsCount": 13,
    "street": "5 Rue du Cardo",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://coach-sportif-nantes-ouest.fr/",
    "phone": "+33 6 48 43 80 21",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach%20Sportif%20Nantes%20Ouest%20SPORTADOM&query_place_id=ChIJfc8Woz3pBUgRDs6MeLqEuq8"
  },
  {
    "title": "JB Coach Sportif Nantes",
    "totalScore": 4.9,
    "reviewsCount": 13,
    "street": "2 Rue Frédéric Mistral",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://coach-sportif-nantes.weeblysite.com/",
    "phone": "+33 6 31 84 30 40",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=JB%20Coach%20Sportif%20Nantes&query_place_id=ChIJ-0O_sVvoBUgRZO2ZaK5cj_E"
  },
  {
    "title": "Anthony Coach Bien-être Coach sportif, Coach de vie, Sophrologue, Praticien PNL, praticien en Hypnose",
    "totalScore": 5.0,
    "reviewsCount": 44,
    "street": "21 Quai de Versailles",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://anthonycoachbienetre.fr/",
    "phone": "+33 6 71 71 72 76",
    "categoryName": "Coach de vie",
    "url": "https://www.google.com/maps/search/?api=1&query=Anthony%20Coach%20Bien-%C3%AAtre%20Coach%20sportif%2C%20Coach%20de%20vie%2C%20Sophrologue%2C%20Praticien%20PNL%2C%20praticien%20en%20Hypnose&query_place_id=ChIJk1BZ-XfuBUgRWiVPW09FM1o"
  },
  {
    "title": "Coach Sam Coach sportif Nantes",
    "totalScore": 5.0,
    "reviewsCount": 16,
    "street": "5 Bd de l'Île",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://coach-sportif-nantes.fr/",
    "phone": "+33 6 82 42 84 51",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach%20Sam%20Coach%20sportif%20Nantes&query_place_id=ChIJPUKBgpXwBUgR1VaSNP2cvFs"
  },
  {
    "title": "EM Sport Coaching - Coach Sportif : Coaching Personnalisé à Nantes ou en Visio",
    "totalScore": 5.0,
    "reviewsCount": 9,
    "street": "31 Rue La Tour d'Auvergne",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://e-msportcoaching.fr/",
    "phone": "+33 6 20 07 83 82",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=EM%20Sport%20Coaching%20-%20Coach%20Sportif%20%3A%20Coaching%20Personnalis%C3%A9%20%C3%A0%20Nantes%20ou%20en%20Visio&query_place_id=ChIJSV5tCB7tBUgReTBohNU8xbo"
  },
  {
    "title": "F Energy Coaching - Coaching sportif à domicile & en extérieur à Nantes",
    "totalScore": 5.0,
    "reviewsCount": 48,
    "street": "16 Rue de la République",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://fenergycoaching.com/",
    "phone": "+33 7 86 31 98 41",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=F%20Energy%20Coaching%20-%20Coaching%20sportif%20%C3%A0%20domicile%20%26%20en%20ext%C3%A9rieur%20%C3%A0%20Nantes&query_place_id=ChIJE_6l9dzuBUgRyNXJzXjmnHY"
  },
  {
    "title": "Cap Excellence Sport - Coaching sportif et préparation physique à Nantes",
    "totalScore": 5.0,
    "reviewsCount": 21,
    "street": "17 Rue Richebourg",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://cap-excellence-sport.com/",
    "phone": "+33 6 63 16 09 33",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Cap%20Excellence%20Sport%20-%20Coaching%20sportif%20et%20pr%C3%A9paration%20physique%20%C3%A0%20Nantes&query_place_id=ChIJ9x7mhPbtBUgR3H6FWzvXUHg"
  },
  {
    "title": "CYGOS Coaching",
    "totalScore": 5.0,
    "reviewsCount": 17,
    "street": "13 Rue du Marchix",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://www.cygos-coaching.fr/",
    "phone": "+33 6 50 19 06 53",
    "categoryName": "Centre de coaching",
    "url": "https://www.google.com/maps/search/?api=1&query=CYGOS%20Coaching&query_place_id=ChIJlZ--AzzsBUgRV-EgFtAx1_8"
  },
  {
    "title": "Body & Mind Coaching - Coaching Sportif et Bien-être à Nantes",
    "totalScore": 5.0,
    "reviewsCount": 15,
    "street": "2 Rue Pitre Chevalier",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://bodyandmindcoaching.fr/",
    "phone": "+33 6 59 20 30 90",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Body%20%26%20Mind%20Coaching%20-%20Coaching%20Sportif%20et%20Bien-%C3%AAtre%20%C3%A0%20Nantes&query_place_id=ChIJd1BfHiTtBUgR3GH50MF7Abo"
  },
  {
    "title": "Charlotte ROUSSEAU Coach Sportive",
    "totalScore": 5.0,
    "reviewsCount": 6,
    "street": "15 Rue Romain Rolland",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://charlottelife-coaching.com/",
    "phone": "+33 6 23 79 39 50",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Charlotte%20ROUSSEAU%20Coach%20Sportive&query_place_id=ChIJQ7lq6KHtBUgRMg9o4JH4jbY"
  },
  {
    "title": "Coach sportif Mounir Bouziane à Nantes, Basse-Goulaine, Vertou, La Haye Fouassière et alentours",
    "totalScore": 5.0,
    "reviewsCount": 13,
    "street": "2 Rue du Général Buat",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://mounir-bouziane.fr/",
    "phone": "+33 7 65 21 86 01",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach%20sportif%20Mounir%20Bouziane%20%C3%A0%20Nantes%2C%20Basse-Goulaine%2C%20Vertou%2C%20La%20Haye%20Fouassi%C3%A8re%20et%20alentours&query_place_id=ChIJmVYL-G_wBUgRUPoidreBAzE"
  },
  {
    "title": "Coach Sportif LLDN",
    "totalScore": 5.0,
    "reviewsCount": 24,
    "street": "23 Av. du Bois Verdot",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.coach-sportif-lldn.fr/",
    "phone": "+33 6 83 36 55 24",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach%20Sportif%20LLDN&query_place_id=ChIJvadmj-XuBUgRkh2fugy-dZ8"
  },
  {
    "title": "HJP-Coaching, Coach Sportif à Nantes",
    "totalScore": 5.0,
    "reviewsCount": 27,
    "street": "6 Rue du Petit Pré",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://www.hjp-coaching.com/",
    "phone": "+33 6 37 49 48 81",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=HJP-Coaching%2C%20Coach%20Sportif%20%C3%A0%20Nantes&query_place_id=ChIJ4yYoSavwBUgRrkKPSeedsZ8"
  },
  {
    "title": "GUMP'S Fitness Coach - Coaching sportif & perte de poids à Nantes",
    "totalScore": 5.0,
    "reviewsCount": 28,
    "street": "20 Rue Lanoue Bras de Fer",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://gumps-fitnesscoach.fr/",
    "phone": "+33 7 83 13 58 05",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=GUMP%27S%20Fitness%20Coach%20-%20Coaching%20sportif%20%26%20perte%20de%20poids%20%C3%A0%20Nantes&query_place_id=ChIJSRkwLEjwBUgRzLmqiXKHbOM"
  },
  {
    "title": "Coaching Sportif EALN",
    "totalScore": 5.0,
    "reviewsCount": 3,
    "street": "14 Rue Teilhard de Chardin",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": null,
    "phone": "+33 6 50 19 76 93",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coaching%20Sportif%20EALN&query_place_id=ChIJ-xg3FcPwBUgR4618EJ2vE2o"
  },
  {
    "title": "Arène Coaching ",
    "totalScore": 5.0,
    "reviewsCount": 4,
    "street": "7 Quai Hoche",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://www.arene-coaching.fr/",
    "phone": "+33 6 74 37 69 28",
    "categoryName": "Coaching professionnel",
    "url": "https://www.google.com/maps/search/?api=1&query=Ar%C3%A8ne%20Coaching%20&query_place_id=ChIJFya5hcPtBUgRpTJnOO19OEo"
  },
  {
    "title": "En forme avec M've Coatching Sportif",
    "totalScore": 5.0,
    "reviewsCount": 4,
    "street": "41 Rue Maréchal Joffre",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": null,
    "phone": "+33 6 74 65 93 47",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=En%20forme%20avec%20M%27ve%20Coatching%20Sportif&query_place_id=ChIJGQfl490ZBUgR_du1NH8PZg4"
  },
  {
    "title": "Thibaut Berard Coach Sportif",
    "totalScore": 5.0,
    "reviewsCount": 4,
    "street": "21 Rue des Hauts Pavés",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": null,
    "phone": "+33 6 14 03 89 57",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Thibaut%20Berard%20Coach%20Sportif&query_place_id=ChIJX3GgducZBUgRHV1GRLyIPVI"
  },
  {
    "title": "Jean-Christophe Cochard Coach Sportif",
    "totalScore": 5.0,
    "reviewsCount": 10,
    "street": "9 Rue des Plantes",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": null,
    "phone": "+33 6 68 43 66 74",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Jean-Christophe%20Cochard%20Coach%20Sportif&query_place_id=ChIJe2fG_kDZBUgRFHYFtIJg7Go"
  },
  {
    "title": "Coach sportif individualisé pour réathlétisation musculaire",
    "totalScore": 5.0,
    "reviewsCount": 4,
    "street": "26 Rue du Capitaine Corhumel",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": null,
    "phone": "+33 6 95 86 32 65",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach%20sportif%20individualis%C3%A9%20pour%20r%C3%A9athl%C3%A9tisation%20musculaire&query_place_id=ChIJvw-IylTZBUgRvzxj7o0VSDY"
  },
  {
    "title": "Coach sportif Nantes | Coaching sportif et nutrition christophe heurtier",
    "totalScore": 5.0,
    "reviewsCount": 4,
    "street": "5 Rue Eugène Pottier",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.coach-sportif-nantes.fr/",
    "phone": "+33 6 22 96 66 88",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach%20sportif%20Nantes%20%7C%20Coaching%20sportif%20et%20nutrition%20christophe%20heurtier&query_place_id=ChIJfT5bBorZBUgRnFusEMOF4t8"
  },
  {
    "title": "Score Training",
    "totalScore": 5.0,
    "reviewsCount": 5,
    "street": "5 Rue Léon Durocher",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://www.score-training.fr/",
    "phone": "+33 6 17 15 41 84",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Score%20Training&query_place_id=ChIJDRaAHuXZBUgRRK0sePsICRQ"
  },
  {
    "title": "JF Coaching",
    "totalScore": 5.0,
    "reviewsCount": 19,
    "street": "3 Rue du Bon Doux",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://jfcoaching-sport.fr/",
    "phone": "+33 6 98 11 69 42",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=JF%20Coaching&query_place_id=ChIJQdRT0K_ZBUgR7CpgjzJCJqg"
  },
  {
    "title": "Steph Coach Travailleurs Handicapés ; Coach Inclusion et Prévention Handicap & RH",
    "totalScore": 5.0,
    "reviewsCount": 19,
    "street": "27 Bd Joliot Curie",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://coachtravailleurshandicapes.fr/",
    "phone": "+33 6 21 57 39 71",
    "categoryName": "Coaching professionnel",
    "url": "https://www.google.com/maps/search/?api=1&query=Steph%20Coach%20Travailleurs%20Handicap%C3%A9s%20%3B%20Coach%20Inclusion%20et%20Pr%C3%A9vention%20Handicap%20%26%20RH&query_place_id=ChIJwXHtY0fZBUgR33XtxPsWp-I"
  },
  {
    "title": "Bonne Mine - Coaching sportif, nutrition et bien-être à Nantes",
    "totalScore": 5.0,
    "reviewsCount": 11,
    "street": "12 Rue Sébastien Gaudais",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.bonneminecoaching.fr/",
    "phone": "+33 6 80 13 11 36",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Bonne%20Mine%20-%20Coaching%20sportif%2C%20nutrition%20et%20bien-%C3%AAtre%20%C3%A0%20Nantes&query_place_id=ChIJOZVvY57ZBUgRKCVoyCzz-kA"
  },
  {
    "title": "ORIGMI Coach Sportif Nantes",
    "totalScore": 5.0,
    "reviewsCount": 2,
    "street": "Rue Molière",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": null,
    "phone": "+33 6 61 48 36 31",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=ORIGMI%20Coach%20Sportif%20Nantes&query_place_id=ChIJfYRtgsTaBUgRH3l25Imd0XQ"
  },
  {
    "title": "Michaël Gauthier coach sportif",
    "totalScore": 5.0,
    "reviewsCount": 2,
    "street": "3 Rue des Pionniers",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": null,
    "phone": "+33 6 27 33 94 24",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Micha%C3%ABl%20Gauthier%20coach%20sportif&query_place_id=ChIJF0-NI6TaBUgRFDBLG-7t0uw"
  },
  {
    "title": "Coaching CYGOS",
    "totalScore": 5.0,
    "reviewsCount": 7,
    "street": "23 Rue du Chanoine Courtonne",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://coachingcygos.fr/",
    "phone": "+33 6 50 19 06 53",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coaching%20CYGOS&query_place_id=ChIJ58NaJlrZBUgRzCceXkc7C7E"
  },
  {
    "title": "Coach sportif pierre léauté pliable sport",
    "totalScore": 5.0,
    "reviewsCount": 10,
    "street": "145 Bd Joliot Curie",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://pierreleautecoachsportifnantes.site-solocal.com/",
    "phone": "+33 6 18 26 88 29",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach%20sportif%20pierre%20l%C3%A9aut%C3%A9%20pliable%20sport&query_place_id=ChIJIQanv5DcBUgR8W8DC5vwHcY"
  },
  {
    "title": "Régis Coach Sportif",
    "totalScore": 5.0,
    "reviewsCount": 5,
    "street": "6 Pl. Anatole France",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": null,
    "phone": "+33 7 82 02 01 56",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=R%C3%A9gis%20Coach%20Sportif&query_place_id=ChIJjyunXarZBUgRw-RW80Hv54Q"
  },
  {
    "title": "FLO Coaching et Formations",
    "totalScore": 5.0,
    "reviewsCount": 3,
    "street": "34 Rue Maréchal Joffre",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.flocoaching.fr/",
    "phone": "+33 6 16 37 41 65",
    "categoryName": "Coaching professionnel",
    "url": "https://www.google.com/maps/search/?api=1&query=FLO%20Coaching%20et%20Formations&query_place_id=ChIJu68e3PZZBUgR9tMr_TUWLXQ"
  },
  {
    "title": "ALCOATCHING - Coach Sportif à Nantes à domicile ou en extérieur",
    "totalScore": 5.0,
    "reviewsCount": 2,
    "street": "13 Rue Alfred de Vigny",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.alcoatching.fr/",
    "phone": "+33 7 86 87 68 03",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=ALCOATCHING%20-%20Coach%20Sportif%20%C3%A0%20Nantes%20%C3%A0%20domicile%20ou%20en%20ext%C3%A9rieur&query_place_id=ChIJpVcQJsFBVUgRYXuHa-DOG0Y"
  },
  {
    "title": "Coach Sportif - Justine Kreisle",
    "totalScore": 5.0,
    "reviewsCount": 1,
    "street": "3 Rue Eugénie Mansion",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://coach-justinekreisle.fr/",
    "phone": "+33 6 07 35 07 77",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach%20Sportif%20-%20Justine%20Kreisle&query_place_id=ChIJ6aBAkRFBVUgRhndyPwaRMyM"
  },
  {
    "title": "Coach sportif Nantes : Japon Athletic",
    "totalScore": 5.0,
    "reviewsCount": 1,
    "street": "1 Rue Juliette Récamier",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://japon-athletic.fr/",
    "phone": "+33 6 17 82 11 59",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach%20sportif%20Nantes%20%3A%20Japon%20Athletic&query_place_id=ChIJ1b2AbrlYVUgR6R-Vz7Ch2RQ"
  },
  {
    "title": "Un esprit dans un corps sain",
    "totalScore": 5.0,
    "reviewsCount": 1,
    "street": "3 Rue Arthur III",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://coach-nantes-piegraphic.business.site/",
    "phone": "+33 6 63 91 31 69",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Un%20esprit%20dans%20un%20corps%20sain&query_place_id=ChIJUwCcLc1YVUgRgXlS1WvGE2I"
  },
  {
    "title": "Coach sportif Nantes - Christophe Piveteau - préparation physique",
    "totalScore": 5.0,
    "reviewsCount": 2,
    "street": "Rue du Frais Bignon",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://christophepiveteaucoachnantes.site-solocal.com/",
    "phone": "+33 6 85 64 94 81",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach%20sportif%20Nantes%20-%20Christophe%20Piveteau%20-%20pr%C3%A9paration%20physique&query_place_id=ChIJbwb4QUtbVUgR1JMZInENCtg"
  },
  {
    "title": "HD coaching | Coaching sportif & Nutrition",
    "totalScore": 5.0,
    "reviewsCount": 1,
    "street": "4 Rue Georges'sand",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.hdcoaching.fr/",
    "phone": "+33 6 88 11 41 53",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=HD%20coaching%20%7C%20Coaching%20sportif%20%26%20Nutrition&query_place_id=ChIJxzMifrxYVUgRnbb7uzMgY84"
  },
  {
    "title": "Coach Sportif - Julien Richard",
    "totalScore": 5.0,
    "reviewsCount": 1,
    "street": "6 Rue de Fontaine Grillée",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.julien-richard-coachsportif.fr/",
    "phone": "+33 6 82 34 79 47",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach%20Sportif%20-%20Julien%20Richard&query_place_id=ChIJj-l8WGpYVUgRAsuFbc_uvMw"
  },
  {
    "title": "Moi Coach - Coaching Sportif à domicile Nantes",
    "totalScore": 5.0,
    "reviewsCount": 3,
    "street": "37 Rue des Châtelliers",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://moi-coachnantes.business.site/?utm_source=gmb&utm_medium=referral",
    "phone": "+33 6 76 13 95 79",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Moi%20Coach%20-%20Coaching%20Sportif%20%C3%A0%20domicile%20Nantes&query_place_id=ChIJzS6HXxRZVUgRrmK-kFAza5c"
  },
  {
    "title": "Sportsmart coaching",
    "totalScore": 4.5,
    "reviewsCount": 2,
    "street": "7 Rue François Rude",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://sportsmart-coaching.business.site/?utm_source=gmb&utm_medium=referral",
    "phone": "+33 6 62 97 10 11",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Sportsmart%20coaching&query_place_id=ChIJyWCG8JpYVUgRrezavn5W96c"
  },
  {
    "title": "Coach sportif Nantes Frédéric Jeux",
    "totalScore": 5.0,
    "reviewsCount": 1,
    "street": "11 Rue Maurice Poulain",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": null,
    "phone": "+33 6 74 51 45 06",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach%20sportif%20Nantes%20Fr%C3%A9d%C3%A9ric%20Jeux&query_place_id=ChIJm4EMbzxYVUgRZd6DadNo3KE"
  }
];

