import { RawLead } from './types';

export const rawLeads: RawLead[] = [
  {
    "title": "Fit-Good",
    "totalScore": 4.9,
    "reviewsCount": 934,
    "street": "11 Rue de la Grande Bretagne",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://fit-good.fr/",
    "phone": "+33 2 40 50 46 99",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Fit-Good+11+Rue+de+la+Grande+Bretagne+Nantes"
  },
  {
    "title": "Batiste Zrn coach sportif santé",
    "totalScore": null,
    "reviewsCount": 0,
    "street": "11 Rue de la Grande Bretagne",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://batistezerren.wixsite.com/coaching",
    "phone": "+33 6 65 51 03 99",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Batiste+Zrn+coach+sportif+santé+11+Rue+de+la+Grande+Bretagne+Nantes"
  },
  {
    "title": "Coach Chloé - COACH SPORTIVE Nantes - Sport Santé",
    "totalScore": 5.0,
    "reviewsCount": 14,
    "street": "Bd Jules Verne",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://coachchloe-sportsante.fr/",
    "phone": "+33 6 58 77 70 90",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach+Chloé+-+COACH+SPORTIVE+Nantes+-+Sport+Santé+Bd+Jules+Verne+Nantes"
  },
  {
    "title": "LIFTRAINER - Coach sportif spécialisé en Street Lifting",
    "totalScore": 5.0,
    "reviewsCount": 80,
    "street": "83 Rue du Perray",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://liftrainer.com/",
    "phone": "+33 6 83 89 08 44",
    "categoryName": "Coaching professionnel",
    "url": "https://www.google.com/maps/search/?api=1&query=LIFTRAINER+-+Coach+sportif+spécialisé+en+Street+Lifting+83+Rue+du+Perray+Nantes"
  },
  {
    "title": "Gaia ATHLETIC TRAINING - Coach sportif/Préparation aux concours/Préparation physique/Réathlétisation",
    "totalScore": 5.0,
    "reviewsCount": 9,
    "street": "La beaujoire",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://gaia-athletictraining.com/",
    "phone": "+33 6 78 30 19 78",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Gaia+ATHLETIC+TRAINING+-+Coach+sportif/Préparation+aux+concours/Préparation+physique/Réathlétisation+La+beaujoire+Nantes"
  },
  {
    "title": "Fred Paul Coaching",
    "totalScore": 4.9,
    "reviewsCount": 21,
    "street": "1 Rue Jeanne la Corsaire",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://www.fredpaul-coaching.com/",
    "phone": "+33 6 77 10 94 02",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Fred+Paul+Coaching+1+Rue+Jeanne+la+Corsaire+Nantes"
  },
  {
    "title": "Keepcool Nantes Beaujoire",
    "totalScore": 4.6,
    "reviewsCount": 249,
    "street": "50 Rte de Carquefou",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.keepcool.fr/s/salle-de-sport-nantes-beaujoire",
    "phone": "+33 2 40 49 36 70",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Keepcool+Nantes+Beaujoire+50+Rte+de+Carquefou+Nantes"
  },
  {
    "title": "Willycoach",
    "totalScore": 5.0,
    "reviewsCount": 46,
    "street": "116 Bd des Belges",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": null,
    "phone": "+33 7 61 91 38 67",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Willycoach+116+Bd+des+Belges+Nantes"
  },
  {
    "title": "Mathis Le Maître Coach Domicil'Gym",
    "totalScore": 5.0,
    "reviewsCount": 20,
    "street": "6 Rue Recteur Schmitt",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.domicilgym.fr/coach-sportif-nantes",
    "phone": "+33 6 22 92 45 37",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Mathis+Le+Maître+Coach+Domicil'Gym+6+Rue+Recteur+Schmitt+Nantes"
  },
  {
    "title": "Nantas Coaching - Coach sportif",
    "totalScore": 5.0,
    "reviewsCount": 11,
    "street": "12 Rue du Port Durand",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": null,
    "phone": "+33 7 82 56 23 35",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Nantas+Coaching+-+Coach+sportif+12+Rue+du+Port+Durand+Nantes"
  },
  {
    "title": "Pierre Girard Coach Sportif",
    "totalScore": 5.0,
    "reviewsCount": 30,
    "street": null,
    "city": null,
    "state": null,
    "countryCode": null,
    "website": "http://pierre-coach-sportif.com/",
    "phone": "+33 6 59 30 18 06",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Pierre+Girard+Coach+Sportif"
  },
  {
    "title": "Prof/Coach badminton",
    "totalScore": 5.0,
    "reviewsCount": 26,
    "street": "5 Rue de la Garde bat",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": null,
    "phone": "+33 6 69 36 23 27",
    "categoryName": "Coaching professionnel",
    "url": "https://www.google.com/maps/search/?api=1&query=Prof/Coach+badminton+5+Rue+de+la+Garde+bat+Nantes"
  },
  {
    "title": "COACH SPORTIF",
    "totalScore": 5.0,
    "reviewsCount": 2,
    "street": "13 Bd du Petit Port",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": null,
    "phone": null,
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=COACH+SPORTIF+13+Bd+du+Petit+Port+Nantes"
  },
  {
    "title": "William Obrist Coach",
    "totalScore": 5.0,
    "reviewsCount": 7,
    "street": "72 Bd des Anglais",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.domicilgym.fr/coach-sportif-nantes/",
    "phone": "+33 7 84 38 33 08",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=William+Obrist+Coach+72+Bd+des+Anglais+Nantes"
  },
  {
    "title": "Mélanie Talhouarn - Coach de vie Confiance en soi | Hypnose | PNL | Bilan de Compétences | Nantes",
    "totalScore": 5.0,
    "reviewsCount": 68,
    "street": "Rue des Plantes",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://melanietalhouarn.fr/",
    "phone": "+33 6 33 88 86 80",
    "categoryName": "Coach de vie",
    "url": "https://www.google.com/maps/search/?api=1&query=Mélanie+Talhouarn+-+Coach+de+vie+Confiance+en+soi+|+Hypnose+|+PNL+|+Bilan+de+Compétences+|+Nantes+Rue+des+Plantes+Nantes"
  },
  {
    "title": "Coach sportif - Jo Coach - Club Garage",
    "totalScore": 4.9,
    "reviewsCount": 15,
    "street": "24 Rue Cardinal Richard",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.jocoach44.com/",
    "phone": "+33 6 67 16 60 18",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach+sportif+-+Jo+Coach+-+Club+Garage+24+Rue+Cardinal+Richard+Nantes"
  },
  {
    "title": "FV Sport Mouvement",
    "totalScore": 4.9,
    "reviewsCount": 39,
    "street": "44 Bd de la Solidarité",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.linkedin.com/in/florian-vernel-38b9aa182/",
    "phone": "+33 6 79 17 04 67",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=FV+Sport+Mouvement+44+Bd+de+la+Solidarité+Nantes"
  },
  {
    "title": "Coach sportif & nutrition Nantes Charles",
    "totalScore": 5.0,
    "reviewsCount": 88,
    "street": "Bd de la Liberté",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://coachsportif.info/",
    "phone": "+33 6 98 91 10 67",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach+sportif+&+nutrition+Nantes+Charles+Bd+de+la+Liberté+Nantes"
  },
  {
    "title": "SPORT ET SANTE NANTES",
    "totalScore": 5.0,
    "reviewsCount": 24,
    "street": "Quai de Versailles",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.sport-sante-nantes.com/",
    "phone": "+33 6 31 41 22 80",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=SPORT+ET+SANTE+NANTES+Quai+de+Versailles+Nantes"
  },
  {
    "title": "Coaching sportif Nantes - Tiphaine J",
    "totalScore": 5.0,
    "reviewsCount": 108,
    "street": "Chem. de la Boucardière",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://coachsportif.info/",
    "phone": "+33 6 30 06 36 71",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coaching+sportif+Nantes+-+Tiphaine+J+Chem.+de+la+Boucardière+Nantes"
  },
  {
    "title": "Mon Coach Nantais",
    "totalScore": 5.0,
    "reviewsCount": 37,
    "street": "4 All. d'Erdre",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://www.moncoachnantais.fr/",
    "phone": "+33 6 45 50 12 40",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Mon+Coach+Nantais+4+All.+d'Erdre+Nantes"
  },
  {
    "title": "Wellness Trainer Studio",
    "totalScore": 5.0,
    "reviewsCount": 25,
    "street": "8 Bd des Tribunes",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://wellness-trainer.fr/",
    "phone": "+33 7 86 53 02 73",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Wellness+Trainer+Studio+8+Bd+des+Tribunes+Nantes"
  },
  {
    "title": "coach sportif Nantes",
    "totalScore": 5.0,
    "reviewsCount": 5,
    "street": "65 Rue de Bel air",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": null,
    "phone": "+33 6 28 69 27 41",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=coach+sportif+Nantes+65+Rue+de+Bel+air+Nantes"
  },
  {
    "title": "Franck ZLATIEW - Préparateur mental",
    "totalScore": 5.0,
    "reviewsCount": 77,
    "street": "72 Av. du Parc de Procé",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://franckzlatiew.com/?utm_source=Fiche+Google&utm_medium=GBP",
    "phone": "+33 6 19 49 73 59",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Franck+ZLATIEW+-+Préparateur+mental+72+Av.+du+Parc+de+Procé+Nantes"
  },
  {
    "title": "Studio Gymbox",
    "totalScore": 5.0,
    "reviewsCount": 146,
    "street": "31 Bd Babin Chevaye",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.studio-gymbox.fr/",
    "phone": "+33 6 89 67 44 68",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Studio+Gymbox+31+Bd+Babin+Chevaye+Nantes"
  },
  {
    "title": "Julien Ferchaud Coach sportif personnel à Nantes",
    "totalScore": 5.0,
    "reviewsCount": 2,
    "street": "6 Rue Villars",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.jfcoach.fr/",
    "phone": "+33 6 17 43 36 69",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Julien+Ferchaud+Coach+sportif+personnel+à+Nantes+6+Rue+Villars+Nantes"
  },
  {
    "title": "Le Coach",
    "totalScore": 5.0,
    "reviewsCount": 4,
    "street": "137 Rue Paul Bellamy",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://fr.coach.com/",
    "phone": "+33 6 78 87 65 12",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Le+Coach+137+Rue+Paul+Bellamy+Nantes"
  },
  {
    "title": "Charly Rabin Coaching Sportif & Massage à domicile",
    "totalScore": 5.0,
    "reviewsCount": 10,
    "street": "2 Rue Damrémont",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://cr-coachsportif-nantes.com/",
    "phone": "+33 6 86 70 59 59",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Charly+Rabin+Coaching+Sportif+&+Massage+à+domicile+2+Rue+Damrémont+Nantes"
  },
  {
    "title": "BMD coaching SPORT SANTE CESU NANTES",
    "totalScore": 5.0,
    "reviewsCount": 41,
    "street": "37 Rue Général Buat",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://bmdcoaching.wixsite.com/website",
    "phone": "+33 6 61 29 56 48",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=BMD+coaching+SPORT+SANTE+CESU+NANTES+37+Rue+Général+Buat+Nantes"
  },
  {
    "title": "AKP Coaching",
    "totalScore": 5.0,
    "reviewsCount": 4,
    "street": "31 Rue du Chemin Rouge",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.espace-isis-nantes.com/",
    "phone": "+33 6 33 22 03 48",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=AKP+Coaching+31+Rue+du+Chemin+Rouge+Nantes"
  },
  {
    "title": "FLAVIEN COACH SPORTIF",
    "totalScore": 5.0,
    "reviewsCount": 8,
    "street": "64 Bd des Belges",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://www.flavien-coach-sportif.com/",
    "phone": "+33 6 27 27 54 85",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=FLAVIEN+COACH+SPORTIF+64+Bd+des+Belges+Nantes"
  },
  {
    "title": "GPC SPORT EN ENTREPRISE",
    "totalScore": 5.0,
    "reviewsCount": 15,
    "street": "143 Bd des Poilus",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.gpcsportsante.com/",
    "phone": "+33 6 31 41 22 80",
    "categoryName": "Centre de coaching",
    "url": "https://www.google.com/maps/search/?api=1&query=GPC+SPORT+EN+ENTREPRISE+143+Bd+des+Poilus+Nantes"
  },
  {
    "title": "OZAPA",
    "totalScore": 5.0,
    "reviewsCount": 1,
    "street": "2 Rte de Paris",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.ozapa.fr/",
    "phone": "+33 7 56 98 44 64",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=OZAPA+2+Rte+de+Paris+Nantes"
  },
  {
    "title": "Anaëlle FORCE - Coach sportif Nantes",
    "totalScore": 5.0,
    "reviewsCount": 16,
    "street": "Bd de Berlin",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": null,
    "phone": "+33 7 77 37 12 27",
    "categoryName": "Coach personnel pour femmes",
    "url": "https://www.google.com/maps/search/?api=1&query=Anaëlle+FORCE+-+Coach+sportif+Nantes+Bd+de+Berlin+Nantes"
  },
  {
    "title": "VDCoach Sportif",
    "totalScore": 5.0,
    "reviewsCount": 1,
    "street": "1 Esp. de la Pierre Percée",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://vdcoach.fr/",
    "phone": "+33 6 62 11 07 86",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=VDCoach+Sportif+1+Esp.+de+la+Pierre+Percée+Nantes"
  },
  {
    "title": "Keepcool Nantes Jules Verne",
    "totalScore": 5.0,
    "reviewsCount": 93,
    "street": "123 Bd Jules Verne",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.keepcool.fr/s/salle-de-sport-nantes-jules-verne",
    "phone": "+33 2 59 16 09 26",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Keepcool+Nantes+Jules+Verne+123+Bd+Jules+Verne+Nantes"
  },
  {
    "title": "Sophie Halley Coach Sportif et Enseignante Pilates",
    "totalScore": 1.0,
    "reviewsCount": 1,
    "street": null,
    "city": null,
    "state": null,
    "countryCode": null,
    "website": "https://www.optisport.fr/coach-sportif/nantes-sophie-halley/",
    "phone": "+33 7 50 42 92 01",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Sophie+Halley+Coach+Sportif+et+Enseignante+Pilates"
  },
  {
    "title": "Studio Sport-Santé / Charlène Houssais",
    "totalScore": 5.0,
    "reviewsCount": 12,
    "street": "5 Av. Lotz Cosse",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.instagram.com/charlene_coachsportif/",
    "phone": "+33 6 46 21 17 81",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Studio+Sport-Santé+/+Charlène+Houssais+5+Av.+Lotz+Cosse+Nantes"
  },
  {
    "title": "Coach sportif à Nantes et préparateur physique - Zebiri",
    "totalScore": 5.0,
    "reviewsCount": 15,
    "street": "20 All. de la Maison Rouge",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://coach-sportif-zebiri.fr/",
    "phone": "+33 7 44 95 21 33",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach+sportif+à+Nantes+et+préparateur+physique+-+Zebiri+20+All.+de+la+Maison+Rouge+Nantes"
  },
  {
    "title": "SebCoaching",
    "totalScore": 4.9,
    "reviewsCount": 8,
    "street": "4 Bd de la Chauvinière",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.sebcoachingnantes.fr/",
    "phone": "+33 6 77 76 00 18",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=SebCoaching+4+Bd+de+la+Chauvinière+Nantes"
  },
  {
    "title": "Coach Sportif - Boxe et Fitness",
    "totalScore": 5.0,
    "reviewsCount": 4,
    "street": "4 All. Germaine de Staël",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.isstraining.fr/accueil",
    "phone": "+33 6 76 51 38 76",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach+Sportif+-+Boxe+et+Fitness+4+All.+Germaine+de+Staël+Nantes"
  },
  {
    "title": "Romain Pénard - Préparation Mentale",
    "totalScore": 5.0,
    "reviewsCount": 9,
    "street": "1 Imp. du Baut",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.rp-prepamentale.fr/",
    "phone": "+33 6 02 26 94 29",
    "categoryName": "Coaching professionnel",
    "url": "https://www.google.com/maps/search/?api=1&query=Romain+Pénard+-+Préparation+Mentale+1+Imp.+du+Baut+Nantes"
  },
  {
    "title": "L'Equilibre Coaching",
    "totalScore": 5.0,
    "reviewsCount": 12,
    "street": null,
    "city": null,
    "state": null,
    "countryCode": null,
    "website": "https://instagram.com/lequilibre_coaching?igshid=ZDdkNTZiNTM=",
    "phone": "+33 6 19 73 76 00",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=L'Equilibre+Coaching"
  },
  {
    "title": "Thibault Conan",
    "totalScore": 5.0,
    "reviewsCount": 22,
    "street": null,
    "city": null,
    "state": null,
    "countryCode": null,
    "website": "https://www.nantes-coachsportif.fr/",
    "phone": "+33 6 69 52 70 50",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Thibault+Conan"
  },
  {
    "title": "ProTrainer",
    "totalScore": 5.0,
    "reviewsCount": 4,
    "street": "14 Rue Alain Barbe Torte",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://protrainer.fr/coach-sportif/pays-de-la-loire/loire-atlantique/nantes",
    "phone": null,
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=ProTrainer+14+Rue+Alain+Barbe+Torte+Nantes"
  },
  {
    "title": "Sophie Coach Sportive Strongwilled coaching",
    "totalScore": 5.0,
    "reviewsCount": 11,
    "street": "12 Bd François Blancho",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://strongwilled-coaching.fr/",
    "phone": null,
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Sophie+Coach+Sportive+Strongwilled+coaching+12+Bd+François+Blancho+Nantes"
  },
  {
    "title": "Greg Coaching - À domicile (CESU) / Studio privé",
    "totalScore": 5.0,
    "reviewsCount": 38,
    "street": "18 Rue du Calvaire",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://www.gregcoaching.fr/",
    "phone": "+33 7 67 29 26 56",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Greg+Coaching+-+À+domicile+(CESU)+/+Studio+privé+18+Rue+du+Calvaire+Nantes"
  },
  {
    "title": "Sport & Esprit by Juliette - Coach sportif à Nantes",
    "totalScore": 5.0,
    "reviewsCount": 58,
    "street": null,
    "city": null,
    "state": null,
    "countryCode": null,
    "website": "https://www.sportetesprit.fr/",
    "phone": "+33 7 64 17 11 82",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Sport+&+Esprit+by+Juliette+-+Coach+sportif+à+Nantes"
  },
  {
    "title": "Keepcool Nantes Saint Mihiel",
    "totalScore": 4.5,
    "reviewsCount": 205,
    "street": "29 Rue Châteaubriand",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.keepcool.fr/s/salle-de-sport-nantes-centre-saint-mihiel/?utm_source=campaign-gmb",
    "phone": "+33 2 28 44 09 95",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Keepcool+Nantes+Saint+Mihiel+29+Rue+Châteaubriand+Nantes"
  },
  {
    "title": "FemiCoach",
    "totalScore": null,
    "reviewsCount": 0,
    "street": "Rue de Strasbourg",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://www.femicoach.fr/",
    "phone": "+33 6 60 59 13 74",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=FemiCoach+Rue+de+Strasbourg+Nantes"
  },
  {
    "title": "Sandy Pruvot - Coaching & Bilan de compétences",
    "totalScore": 5.0,
    "reviewsCount": 5,
    "street": "13 Rue de la Beraudière",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://priorise.fr/praticiens/sandy-pruvot/#a-propos",
    "phone": "+33 6 78 77 37 34",
    "categoryName": "Coaching professionnel",
    "url": "https://www.google.com/maps/search/?api=1&query=Sandy+Pruvot+-+Coaching+&+Bilan+de+compétences+13+Rue+de+la+Beraudière+Nantes"
  },
  {
    "title": "Coach sportif nantes / coach nantes",
    "totalScore": null,
    "reviewsCount": 0,
    "street": "26 Bd Gabriel Guist'Hau",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://www.jrgym.fr/",
    "phone": "+33 6 64 97 34 36",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach+sportif+nantes+/+coach+nantes+26+Bd+Gabriel+Guist'Hau+Nantes"
  },
  {
    "title": "STUDIO JMH - JMH PERSONAL TRAINER",
    "totalScore": 5.0,
    "reviewsCount": 21,
    "street": "28 Rue Félibien",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://www.jmh-personaltrainer.com/",
    "phone": "+33 7 89 02 47 09",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=STUDIO+JMH+-+JMH+PERSONAL+TRAINER+28+Rue+Félibien+Nantes"
  },
  {
    "title": "Healthylink",
    "totalScore": 5.0,
    "reviewsCount": 30,
    "street": "8 Rue de Budapest",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://www.healthylink.fr/",
    "phone": "+33 6 20 61 27 58",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Healthylink+8+Rue+de+Budapest+Nantes"
  },
  {
    "title": "S.D Coaching",
    "totalScore": 5.0,
    "reviewsCount": 2,
    "street": "1 Rue Anatole de Monzie",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.sd-coaching.fr/",
    "phone": "+33 7 66 84 00 59",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=S.D+Coaching+1+Rue+Anatole+de+Monzie+Nantes"
  },
  {
    "title": "Alice DA COSTA",
    "totalScore": 5.0,
    "reviewsCount": 35,
    "street": "Fitness Park Beaulieu",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://linktr.ee/Alice_COACH?utm_source=linktree_profile_share&ltsid=d5a3db52-3872-463d-b2df-239e2cc9e10c",
    "phone": "+33 6 17 21 70 32",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Alice+DA+COSTA+Fitness+Park+Beaulieu+Nantes"
  },
  {
    "title": "Anne Gobled Coaching",
    "totalScore": 5.0,
    "reviewsCount": 40,
    "street": "Espace NOW COWORKING, 61 Bd de la Prairie au Duc",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://annegobled.com/",
    "phone": "+33 6 20 93 56 38",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Anne+Gobled+Coaching+Espace+NOW+COWORKING,+61+Bd+de+la+Prairie+au+Duc+Nantes"
  },
  {
    "title": "Alexandre Talet Coach Sportif",
    "totalScore": 4.8,
    "reviewsCount": 20,
    "street": null,
    "city": null,
    "state": null,
    "countryCode": null,
    "website": "https://www.domicilgym.fr/coach-sportif-nantes",
    "phone": "+33 7 60 18 66 02",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Alexandre+Talet+Coach+Sportif"
  },
  {
    "title": "Studio Jive Planet - électrostimulation & nutrition | Nantes",
    "totalScore": 5.0,
    "reviewsCount": 90,
    "street": "3 Rue d'Aunis",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://www.jiveplanetstudio-nantes.fr/",
    "phone": "+33 6 86 07 43 92",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Studio+Jive+Planet+-+électrostimulation+&+nutrition+|+Nantes+3+Rue+d'Aunis+Nantes"
  },
  {
    "title": "Coaching professionnel - Maison du coaching",
    "totalScore": null,
    "reviewsCount": 0,
    "street": "11 Rue du Calvaire",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.maisonducoaching.fr/?utm_medium=referral&utm_source=gmb",
    "phone": "+33 2 85 52 31 05",
    "categoryName": "Coaching professionnel",
    "url": "https://www.google.com/maps/search/?api=1&query=Coaching+professionnel+-+Maison+du+coaching+11+Rue+du+Calvaire+Nantes"
  },
  {
    "title": "Wyldside",
    "totalScore": 5.0,
    "reviewsCount": 23,
    "street": null,
    "city": null,
    "state": null,
    "countryCode": null,
    "website": "https://www.wyldside44.fr/",
    "phone": "+33 7 69 51 57 57",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Wyldside"
  },
  {
    "title": "Amandine Gicquel - Le Coaching au féminin",
    "totalScore": 5.0,
    "reviewsCount": 47,
    "street": "61 Rue Edgar Quinet",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "http://www.lecoachingaufeminin.fr/",
    "phone": "+33 6 60 93 61 89",
    "categoryName": "Coach de vie",
    "url": "https://www.google.com/maps/search/?api=1&query=Amandine+Gicquel+-+Le+Coaching+au+féminin+61+Rue+Edgar+Quinet+Nantes"
  },
  {
    "title": "Thibault Fauvel",
    "totalScore": 5.0,
    "reviewsCount": 2,
    "street": "8 Rue Evariste Luminais",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.instagram.com/thibault_fauvel_coaching/?hl=fr",
    "phone": "+33 6 68 03 73 78",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Thibault+Fauvel+8+Rue+Evariste+Luminais+Nantes"
  },
  {
    "title": "Coach professionnelle Nantes | Stéphanie HERVÉ-PINEAU – PITCHI – Assertivité · Négociation · Leadership",
    "totalScore": 5.0,
    "reviewsCount": 19,
    "street": "20 bis Bd de Launay",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://pitchi.fr/",
    "phone": "+33 6 69 67 14 49",
    "categoryName": "Coaching professionnel",
    "url": "https://www.google.com/maps/search/?api=1&query=Coach+professionnelle+Nantes+|+Stéphanie+HERVÉ-PINEAU+–+PITCHI+–+Assertivité+·+Négociation+·+Leadership+20+bis+Bd+de+Launay+Nantes"
  },
  {
    "title": "Simon Pelé - Préparateur mental, Coach particulier",
    "totalScore": 4.7,
    "reviewsCount": 28,
    "street": "47 Rue du Coteau",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://simon-prepamentale.fr/",
    "phone": "+33 6 51 98 54 23",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Simon+Pelé+-+Préparateur+mental,+Coach+particulier+47+Rue+du+Coteau+Nantes"
  },
  {
    "title": "Karine Vi",
    "totalScore": 5.0,
    "reviewsCount": 3,
    "street": "2 Rue Basile Valentin",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://karine-vi-pilates.jimdosite.com/",
    "phone": "+33 7 88 94 52 45",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Karine+Vi+2+Rue+Basile+Valentin+Nantes"
  },
  {
    "title": "Coaching Sportif Nantes - Educateur Sportif",
    "totalScore": null,
    "reviewsCount": 0,
    "street": null,
    "city": null,
    "state": null,
    "countryCode": null,
    "website": null,
    "phone": "+33 7 84 59 10 47",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Coaching+Sportif+Nantes+-+Educateur+Sportif"
  },
  {
    "title": "Thibault Theresy - kinésithérapeute du sport et préparateur physique",
    "totalScore": 5.0,
    "reviewsCount": 56,
    "street": "Kiné Nantes Bellevue, 20 Rue de l'Hérault",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://www.doctolib.fr/masseur-kinesitherapeute/paris/thibault-theresy-paris",
    "phone": "+33 7 56 85 56 00",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Thibault+Theresy+-+kinésithérapeute+du+sport+et+préparateur+physique+Kiné+Nantes+Bellevue,+20+Rue+de+l'Hérault+Nantes"
  },
  {
    "title": "Φ Trainer",
    "totalScore": null,
    "reviewsCount": 0,
    "street": null,
    "city": null,
    "state": null,
    "countryCode": null,
    "website": null,
    "phone": "+33 7 67 77 29 68",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Φ+Trainer"
  },
  {
    "title": "Jamet Sporting Club",
    "totalScore": 5.0,
    "reviewsCount": 50,
    "street": "21 Bd Emile Romanet",
    "city": "Nantes",
    "state": null,
    "countryCode": "FR",
    "website": "https://gymnase-jamet.fr/",
    "phone": "+33 7 87 64 54 31",
    "categoryName": "Coach particulier",
    "url": "https://www.google.com/maps/search/?api=1&query=Jamet+Sporting+Club+21+Bd+Emile+Romanet+Nantes"
  }
];
